# -*- coding: utf-8 -*-
"""Visualize_learnt_CNN_filters.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lDv-V08OJi9VNzANnMCz0OMn236G68AR
"""

# Import VGG model
from keras.applications.vgg16 import VGG16
# Create model
model = VGG16()
# View model
model.summary()

filters, biases = model.layers[1].get_weights()

filters.shape

filters.min(), filters.max(), biases.min(), biases.max()

filters_min, filters_max = filters.min(), filters.max()
filters = (filters - filters_min) / (filters_max - filters_min)

n_filters = 15
ith = 1

from matplotlib import pyplot
for i in range(n_filters):
  f = filters[:, :, :, i]
  for j in range(3):
    aplot = pyplot.subplot(n_filters, 3, ith)
    aplot.set_xticks([])
    aplot.set_yticks([])
    pyplot.imshow(f[:,:,j], cmap='gray')
    ith += 1
pyplot.show()

from keras.models import Model
model = Model(inputs=model.inputs, outputs=model.layers[1].output)

from keras.preprocessing.image import load_img, img_to_array

img = load_img("bird.jpeg", target_size=(224, 224))

pyplot.imshow(img)

from keras.applications.vgg16 import preprocess_input
from numpy import expand_dims

img = img_to_array(img)
img = expand_dims(img, axis=0)
img = preprocess_input(img)

model.summary()

features = model.predict(img)

nmap = 8
ith = 1

for i in range(nmap):
  for j in range(nmap):
    amap = pyplot.subplot(nmap, nmap, ith)
    amap.set_xticks([])
    amap.set_yticks([])
    pyplot.imshow(features[0, :, :, ith-1], cmap='gray')
    ith += 1

pyplot.show()

img = load_img("elephant.jpeg", target_size=(224, 224))

pyplot.imshow(img)

img = img_to_array(img)
img = expand_dims(img, axis=0)
img = preprocess_input(img)

features = model.predict(img)

map_dim = 8
ith = 1

for i in range(map_dim):
  for j in range(map_dim):
    aplt = pyplot.subplot(map_dim, map_dim, ith)
    aplt.set_xticks([])
    aplt.set_yticks([])
    pyplot.imshow(features[0,:,:,ith-1], cmap="gray")
    ith += 1

pyplot.show()

img = load_img("hiccup.jpg", target_size=(224, 224))

pyplot.imshow(img)

img = img_to_array(img)
img = expand_dims(img, axis=0)
img = preprocess_input(img)

features = model.predict(img)

map_dim = 8
ith = 1

for i in range(map_dim):
  for j in range(map_dim):
    aplt = pyplot.subplot(map_dim, map_dim, ith)
    aplt.set_xticks([])
    aplt.set_yticks([])
    pyplot.imshow(features[0,:,:,ith-1], cmap="gray")
    ith += 1

pyplot.show()

img = load_img("2subjects.jpg", target_size=(224, 224))

pyplot.imshow(img)

img = img_to_array(img)
img = expand_dims(img, axis=0)
img = preprocess_input(img)

features = model.predict(img)

map_dim = 8
ith = 1

for i in range(map_dim):
  for j in range(map_dim):
    aplt = pyplot.subplot(map_dim, map_dim, ith)
    aplt.set_xticks([])
    aplt.set_yticks([])
    pyplot.imshow(features[0,:,:,ith-1], cmap="gray")
    ith += 1

pyplot.show()

